Repository shhossain/computer_science, pull requests merged in 2022-10, with the labels that each got.

#29 contributed topic cloud computing
  Cloud Computing/Readme.md
Labels: hacktoberfest-accepted

#32 Added Fibonacci Sequence Algorithm in Dynamic Programming
  Algorithms/Dynamic Programming/Fibonacci Sequence/README.md
  Algorithms/Dynamic Programming/README.md
  Algorithms/readme.md
Labels: hacktoberfest-accepted

#37 Added info the conditional statements and loops.
  Statements and Functions/readme.md
  readme.md
Labels: hacktoberfest-accepted

#46 Updated Tree, Heap
  Data Structures/Heap.md
  Data Structures/Tree.md
  Data Structures/readme.md
Labels: hacktoberfest-accepted

#52 Added Shell Sort Algorithm
  Algorithms/Sorting/ShellSort/readme.md
  Algorithms/Sorting/readme.md
  Algorithms/readme.md
Labels: hacktoberfest-accepted

#68 Added Functions and OOPs
  Object Oriented Programming/readme.md
  Statements and Functions/readme.md
  readme.md
Labels: hacktoberfest-accepted

#71 Added Count Sort
  Algorithms/Sorting/CountSort/readme.md
  Algorithms/Sorting/readme.md
  Algorithms/readme.md
Labels: hacktoberfest-accepted

#72 The Knight’s tour problem - Backtracking added
  Algorithms/Backtracking/The Knight’s tour problem/README.md
Labels: hacktoberfest-accepted

#92 Add Coin Change
  Algorithms/Dynamic Programming/Coin Change/README.md
Labels: enhancement, hacktoberfest-accepted

#43 Update readme.md
  Data Structures/readme.md
Labels: enhancement

#127 Updated Time Complexity Readme file
  Algorithms/Time Complexity/readme.md
Labels: hacktoberfest-accepted

#142 Add Dijkstra's Algorithm
  Algorithms/Graphs/Traversal Algorithms/Dijkstra'sAlgorithm/readme.md
  Algorithms/Graphs/Traversal Algorithms/readme.md
  Algorithms/Graphs/readme.md
Labels: hacktoberfest-accepted

#145 Adding network and networking protocols resource #137
  Networking/readme.md
  readme.md
Labels: hacktoberfest-accepted

#147 Add Bellman Ford Algorithm
  Algorithms/Graphs/Shortest Path/BellmanFordAlgorithm/readme.md
  Algorithms/Graphs/Shortest Path/readme.md
  Algorithms/Graphs/readme.md
Labels: hacktoberfest-accepted

#164 Add A* Search
  Algorithms/Graphs/Traversal Algorithms/AstarSearch/readme.md
  Algorithms/Graphs/Traversal Algorithms/readme.md
Labels: hacktoberfest-accepted

#181 Added the topic : ER-Model
  DBMS/ER Model/12310.png
  DBMS/ER Model/33333-1.png
  DBMS/ER Model/Database-Management-S-ystem-ER-Model-9.png
  DBMS/ER Model/Database-Management-System-ER-Model-10.png
  DBMS/ER Model/Database-Management-System-ER-Model-12.png
  DBMS/ER Model/Database-Management-System-ER-Model-13.png
  DBMS/ER Model/Database-Management-System-ER-Model-14.png
  DBMS/ER Model/Database-Management-System-ER-Model-15.png
  DBMS/ER Model/Database-Management-System-ER-Model-16.png
  DBMS/ER Model/Database-Management-System-ER-Model-17.png
  DBMS/ER Model/Database-Management-System-ER-Model-18.png
  DBMS/ER Model/Database-Management-System-ER-Model-2.png
  DBMS/ER Model/Database-Management-System-ER-Model-3.png
  DBMS/ER Model/Database-Management-System-ER-Model-4.png
  DBMS/ER Model/Database-Management-System-ER-Model-5.png
  DBMS/ER Model/Database-Management-System-ER-Model-6.png
  DBMS/ER Model/Database-Management-System-ER-Model-7.png
  DBMS/ER Model/Database-Management-System-ER-Model-8.png
  DBMS/ER Model/Database-Management-System-ER-Model.png
  DBMS/ER Model/readme.md
Labels: hacktoberfest-accepted

#185 Added a folder on divide and conquer and added one example problem
  Algorithms/Divide and Conquer/Maximum and minium of an array/readme.md
  Algorithms/Divide and Conquer/readme.md
Labels: hacktoberfest-accepted

#197 Update Greedy Algorithm
  Algorithms/Greedy Algorithm/Ford-Fulkerson/readme.md
Labels: hacktoberfest-accepted

#199 Added Knapsack Problem Algorithm
  Algorithms/Dynamic Programming/Knapsack Problem/README.md
  Algorithms/Dynamic Programming/README.md
Labels: hacktoberfest-accepted

#215 added edit distance, LIS and matrix chain multiplication in dynamic p…
  Algorithms/Dynamic Programming/Edit Distance/README.md
  Algorithms/Dynamic Programming/Longest Increasing Subsequence/README.md
  Algorithms/Dynamic Programming/Matrix Chain Multiplication/README.md
  Algorithms/Dynamic Programming/README.md
Labels: hacktoberfest-accepted

#216 Articulation points
  Algorithms/Graphs/Articulation Points/readme.md
Labels: hacktoberfest-accepted

#208 Added Sliding Window
  Algorithms/Sliding Window Algorithm/Fixed Length/Maximum Sum Subarray (K)/readme.md
  Algorithms/Sliding Window Algorithm/Fixed Length/readme.md
  Algorithms/Sliding Window Algorithm/Variable Length/Largest Subarray Sum (K)/readme.md
  Algorithms/Sliding Window Algorithm/Variable Length/readme.md
  Algorithms/Sliding Window Algorithm/readme.md
Labels: hacktoberfest-accepted

#222 Added Sudoku Algorithm
  Algorithms/Backtracking/README.md
  Algorithms/Backtracking/Sudoku/readme.md
Labels: hacktoberfest-accepted

#225 Added Java Code
  Algorithms/Backtracking/Sudoku/readme.md
Labels: hacktoberfest-accepted

#233 New
  Algorithms/Searching/BinarySearch/readme.md
  Algorithms/Searching/SequentialSearch/readme.md
  Algorithms/Searching/readme.md
  Algorithms/Sorting/ShellSort/readme.md
  Algorithms/Sorting/readme.md
  Algorithms/readme.md
  readme.md
Labels: hacktoberfest-accepted

#238 Bellman ford algorithm
  Algorithms/Graphs/Bellman-Ford Algorithm/readme.md
Labels: hacktoberfest-accepted

#258 Python code added in Sudoku algorithm
  Algorithms/Backtracking/Sudoku/readme.md
Labels: hacktoberfest-accepted

#266 Added a divide and conquer algorithm strassen's matrix multiplication
  Algorithms/Divide and Conquer/Strassen's Algorithm/readme.md
Labels: hacktoberfest-accepted

#291 Update Readme.md ,added C code
  Algorithms/Dynamic Programming/Floyd Warshall Algorithm/readme.md
Labels: hacktoberfest-accepted

#292 Update Readme.md
  Algorithms/Dynamic Programming/Floyd Warshall Algorithm/readme.md
Labels: hacktoberfest-accepted

#293 Update Readme.md
  Algorithms/Dynamic Programming/Floyd Warshall Algorithm/readme.md
Labels: hacktoberfest-accepted

#299 Added csharp code
  Algorithms/Backtracking/Tug of War/README.md
Labels: hacktoberfest-accepted

#305 Fix the markdown in readme for Sequential sort.
  Algorithms/Searching/SequentialSearch/readme.md
Labels: hacktoberfest-accepted

#325 Word Boggle (Backtracking Problem) Solution
  Algorithms/Backtracking/Generate IP Adresses/README.md
  Algorithms/Backtracking/Permutation Of a Given String/README.md
  Algorithms/Word Boggle/README.md
Labels: Merge Conflicts

#352 javscript code added ---rkh
  Algorithms/Backtracking/Sudoku/readme.md
Labels: Merge Conflicts

#359 added c# ---rkh
  Algorithms/Backtracking/Sudoku/readme.md
  Algorithms/Sliding Window Algorithm/Fixed Length/Maximum Sum Subarray (K)/readme.md
Labels: Merge Conflicts

#399 Update readme.md
  DBMS/Database Management System/readme.md
Labels: Merge Conflicts

#415 IP address generating algorithm is added to readme file
  Algorithms/Backtracking/README.md
Labels: kind/documentation, size/XS

#416 Remove Invalid Parentheses added
  Algorithms/Backtracking/Remove Invalid Parentheses/README.md
Labels: kind/documentation, size/L

#418 Longest Possible Route in a Matrix with Hurdles Added
  Longest Possible Route in a Matrix with Hurdles/README.md
Labels: kind/documentation, size/L

#419 Remove Invalid Parentheses added in readme file
  Algorithms/Backtracking/README.md
Labels: kind/documentation, size/XS

#421 Magnet Puzzle added with correct output
  Algorithms/Backtracking/Magnet Puzzle/README.md
Labels: kind/documentation, size/L

#430 implementation of Knapsack problem using JAVA
  Algorithms/Branch and Bound/Knapsack Problem/README.md
Labels: kind/documentation, size/L

#429 Update readme.md
  Object Oriented Programming/readme.md
Labels: kind/documentation, size/XS

#428 Update readme.md
  Object Oriented Programming/readme.md
Labels: kind/documentation, size/XS

#427 Update readme.md
  Web Technology/WebTechnology.md
Labels: kind/documentation, size/XS

#425 Update readme.md
  Cloud Computing/Readme.md
Labels: kind/documentation, size/XS

#424 Update readme.md
  Boolean Logic/readme.md
Labels: kind/documentation, size/XS

#435 Update readme.md
  Networking/OSI Model/readme.md
Labels: kind/documentation, size/XS

#434 Update readme.md
  Instruction Set/readme.md
Labels: kind/documentation, size/XS

#436 Update readme.md
  Cryptography/readme.md
Labels: kind/documentation, size/XS

#533 Test Code
  .github/test_code.py
  .github/workflows/test_code.yml
Labels: kind/feature, size/XL

#538 Typo
  Algorithms/Backtracking/README.md
  Algorithms/Backtracking/Sudoku/readme.md
Labels: kind/documentation, size/S

#539 Updated Ford-Fulkerson Algorithm in ReadMe
  Algorithms/readme.md
Labels: kind/documentation, size/XS

#541 Added somemore insights on cache memory of the read me file
  README.md
Labels: kind/documentation, size/S

#542 Adding insights on Cloud Computing
  README.md
Labels: kind/documentation, size/M

#545 Added information about layer 4, 5, 6, 7 to networking
  Networking/readme.md
Labels: kind/documentation, size/M

#549 Updated Machine Learning section.
  README.md
Labels: kind/documentation, size/M

#551 Pubic blockchain
  Cryptography/readme.md
Labels: kind/documentation, size/S

#552 Added extra commits on private blockchain and added permissioned bloc…
  Cryptography/readme.md
Labels: kind/documentation, size/M

#554 Removal of C++ from Longest Common Subsequence
  Algorithms/Dynamic Programming/Longest Common Subsequence/README.md
Labels: kind/documentation, size/S

#556 Removal of C# from Duffman Coding
  Algorithms/Greedy Algorithm/Huffman Coding Algorithm/readme.md
Labels: kind/documentation, size/L

#557 Explained ACID properties and examples in DBMS section
  DBMS/Database Management System/readme.md
Labels: kind/documentation, size/M

#558 Added and improved the CPU section
  CPU/readme.md
Labels: kind/documentation, size/XS

#561 Kruskal Algorithm, removal of Java
  Algorithms/Greedy Algorithm/Krushkal's Algorithm/readme.md
Labels: kind/documentation, size/L

#562 Added section on Theory of Computation
  README.md
Labels: kind/documentation, size/S

#564 Corrected name collision under windows
  Algorithms/Dynamic Programming/Coin Change/README.md
  README.md
Labels: kind/documentation, size/L

#566 Removal of C & Java from Ford-Fulkerson Algorithm
  Algorithms/Greedy Algorithm/Ford-Fulkerson/readme.md
Labels: kind/documentation, size/L

#567 Polished the Time Complexity and Space Complexity Section
  README.md
Labels: kind/documentation, size/S

#570 Clarified a couple points and polished Array.md
  Data Structures/Array.md
Labels: kind/documentation, size/M

#571 Clarified info in HashTable.md
  Data Structures/HashTable.md
Labels: kind/documentation, size/M
