Repository shhossain/computer_science, pull requests merged in 2023-10, with the labels that each got.

#638 Adding multi cloud details
  Cloud Computing/Readme.md
Labels: kind/documentation, size/XS

#643 Created a new section for Signedness
  Data Types/readme.md
Labels: kind/documentation, size/M

#637 French translation
  Programming_Languages/readme_fr.md
  README.md
  README_fr.md
Labels: kind/documentation, size/L

#646 Added How a system boots up. This is corresponding to the issue 642. …
  Operating Systems/os_boot_process.md
  Operating Systems/readme.md
Labels: kind/documentation, size/M

#648 Added information related to cache
  Registers Cache and RAM/readme.md
Labels: kind/feature, size/S

#650 added new readme in tamil
  README.md
  README_ta.md
Labels: kind/documentation, size/XL

#651 added 404 and Three js in to web markdown
  Internet/readme.md
  Web Technology/WebTechnology.md
Labels: kind/documentation, size/M

#655 added new readme in gujarati
  README.md
  README_guj.md
Labels: kind/documentation

#656 added number system conversion for 6 languages C, CPP , JS, TS, Lua, Java
  Number System/Conversion_In_C.c
  Number System/Conversion_In_JS.js
  Number System/Conversion_In_Java.java
  Number System/Conversion_In_TS.ts
  Number System/Conversion_In_c++.cpp
  Number System/Convesion_In_Lua.lua
  Number System/readme.md
Labels: kind/feature

#660 updated the 404 Readmi and programming languages readmi
  Programming_Languages/readme.md
Labels: kind/documentation, size/L

#662 Added information related to UDP
  Networking/UDP/UDP.png
  Networking/UDP/udp.md
  Networking/readme.md
Labels: size/M, kind/feature

#661 Added functional programing
  Functional Programing/readme.md
Labels: size/L, kind/feature

#654 String based Algorithms added
  Algorithms/String Based Algorithms/KMP/readme.md
  Algorithms/String Based Algorithms/RabinKarp/readme.md
  Algorithms/String Based Algorithms/readme.md
  README.md
Labels: kind/documentation, size/L

#668 Changed the Memory & Storage Section
  Memory and Storage/readme.md
Labels: kind/documentation, size/L

#664 Create Main.py
  Object Oriented Programming/Word_Predictor/main.py
  Object Oriented Programming/readme.md
Labels: size/L

#670 Readme translated to portuguese lang
  README.md
  README_pt.md
Labels: kind/documentation

#672 Naive Searching algorithm in string added
  Algorithms/String Based Algorithms/NaiveSearching/readme.md
  Algorithms/String Based Algorithms/readme.md
Labels: kind/documentation, size/M

#673 Resolved the issue of adding about HTTP - HTTPS
  Networking/HTTP-HTTPS/https.md
Labels: kind/documentation, size/M

#674 Update Graph.md
  Data Structures/Graph.md
Labels: kind/documentation, size/L

#679 feat: Add README in Romanian language
  README.md
  README_ro.md
Labels: kind/documentation, size/XL

#684 added information about cookies in https.md in Networking
  Networking/HTTP-HTTPS/https.md
Labels: kind/documentation, size/S

#685 fix language files
  README_bn.md
  README_es.md
  README_fr.md
  README_guj.md
  README_pt.md
  README_ta.md
Labels: kind/documentation, size/M

#689 readme.md translated into Tamil language
  README.md
  README_te.md
Labels: kind/documentation

#686 Added Hindi translation of READme.md
  README.md
  README_hi.md
Labels: kind/documentation, size/L

#695 Divide and conquer update
  Algorithms/Divide and Conquer/Inversion Problem/readme.md
  Algorithms/Divide and Conquer/readme.md
  Algorithms/Sorting/MergeSort/readme.md
Labels: kind/documentation, size/L

#699 Added examples to cloud services and deployment models
  Cloud Computing/README.md
Labels: kind/documentation, size/S

#698 Fix: syntax highlighting
  Algorithms/Searching/LinearSearch/readme.md
Labels: kind/documentation, size/L

#697 Added more simplified example to OOPS
  Object Oriented Programming/Online_Bookstore/main.py
  Object Oriented Programming/readme.md
Labels: kind/documentation, size/M

#705 PriorityQueue.md
  Data Structures/PriorityQueue.md
Labels: kind/documentation, size/L

#711 Create readme.md for suffix trie
  Algorithms/String Based Algorithms/SuffixTrie/readme.md
Labels: kind/documentation, size/M

#713 Added Tree Based Algorithms under graph in Algorithms
  Algorithms/Graphs/Tree Based Algorithms/Traversal/readme.md
  Algorithms/Graphs/Tree Based Algorithms/readme.md
Labels: kind/documentation, size/M

#716 fix modified
  .github/test_code.py
Labels: kind/documentation, size/L

#717 Revert "fix modified"
  .github/test_code.py
Labels: size/L, kind/bug

#718 fix test_code 2
  .github/test_code.py
Labels: size/S, kind/bug

#719 Test code
  .github/test_code.py
  Number System/Conversion_In_Python1.py
  Number System/Conversion_In_Python2.py
Labels: size/L, kind/feature
